services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: taxi-driver-postgres
    environment:
      POSTGRES_DB: taxi_driver
      POSTGRES_USER: taxi_user
      POSTGRES_PASSWORD: taxi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taxi_user -d taxi_driver"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # API FastAPI
  taxi-driver-api:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    container_name: taxi-driver-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://taxi_user:taxi_password@postgres:5432/taxi_driver
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=taxi_driver
      - POSTGRES_USER=taxi_user
      - POSTGRES_PASSWORD=taxi_password
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
